#pragma once

#include "ProcessorBase.h"
#include "AddProcessor.h"
#include "CompressorProcessor.h"
#include "DelayProcessor.h"
#include "FaustProcessor.h"
#include "FilterProcessor.h"
#include "OscillatorProcessor.h"
#include "PlaybackProcessor.h"
#include "PlaybackWarpProcessor.h"
#include "PluginProcessor.h"
#include "RecorderProcessor.h"
#include "ReverbProcessor.h"
#include "PannerProcessor.h"
#include "SamplerProcessor.h"